version: '2'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/workshop
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - workshop
volumes:
  data: